import React from "react";
import { Composition } from "remotion";
import { Walkthrough, WT_FPS, WT_W, WT_H, wtDuration } from "./Walkthrough.jsx";
import { WALKTHROUGHS } from "./walkthrough.data.js";

// One composition per captured feature: id = "WT-<id>". Remotion ids cannot
// contain "_". WALKTHROUGHS is generated by `node walkthrough.mjs` (the capturer).
export const RemotionRoot = () => (
  <>
    {WALKTHROUGHS.map((w) => (
      <Composition
        key={"WT-" + w.id}
        id={"WT-" + w.id}
        component={Walkthrough}
        durationInFrames={Math.max(1, wtDuration(w))}
        fps={WT_FPS}
        width={WT_W}
        height={WT_H}
        defaultProps={{ wt: w }}
      />
    ))}
  </>
);
