import React from "react";
import { Composition } from "remotion";
import { Walkthrough, WT_FPS, WT_W, WT_H, wtDuration } from "./Walkthrough.jsx";
import { WALKTHROUGHS } from "./walkthrough.data.js";
import { Walkthrough2up, WT2_FPS, WT2_W, WT2_H, wt2Duration } from "./Walkthrough2up.jsx";
import { COLLAB_WALKTHROUGHS } from "./walkthrough.collab.data.js";

// One composition per captured feature: id = "WT-<id>" (single-pane) and "WTC-<id>"
// (multi-pane collab). Remotion ids cannot contain "_". WALKTHROUGHS is generated by
// `node walkthrough.mjs`; COLLAB_WALKTHROUGHS by `node walkthrough.collab.mjs`.
export const RemotionRoot = () => (
  <>
    {WALKTHROUGHS.map((w) => (
      <Composition
        key={"WT-" + w.id}
        id={"WT-" + w.id}
        component={Walkthrough}
        durationInFrames={Math.max(1, wtDuration(w))}
        fps={WT_FPS}
        width={WT_W}
        height={WT_H}
        defaultProps={{ wt: w }}
      />
    ))}
    {COLLAB_WALKTHROUGHS.map((w) => (
      <Composition
        key={"WTC-" + w.id}
        id={"WTC-" + w.id}
        component={Walkthrough2up}
        durationInFrames={Math.max(1, wt2Duration(w))}
        fps={WT2_FPS}
        width={WT2_W}
        height={WT2_H}
        defaultProps={{ wt: w }}
      />
    ))}
  </>
);
