// AUTO-GENERATED by walkthrough.collab.mjs — do not edit by hand.
export const COLLAB_WALKTHROUGHS = [
  {
    "id": "LiveSync",
    "title": "Live Collaboration",
    "accent": "#10b981",
    "vw": 1280,
    "vh": 600,
    "cropVH": 360,
    "paneLabels": [
      "Client A",
      "Client B"
    ],
    "steps": [
      {
        "caption": "Two clients, one shared board",
        "hold": 70,
        "burst": false,
        "panes": [
          {
            "img": "wt-collab/LiveSync/p0_00.png",
            "cursor": null,
            "click": false
          },
          {
            "img": "wt-collab/LiveSync/p1_00.png",
            "cursor": null,
            "click": false
          }
        ]
      },
      {
        "caption": "Client A types a new card",
        "hold": 60,
        "burst": false,
        "panes": [
          {
            "img": "wt-collab/LiveSync/p0_01.png",
            "cursor": {
              "x": 537,
              "y": 99
            },
            "click": false
          },
          {
            "img": "wt-collab/LiveSync/p1_01.png",
            "cursor": null,
            "click": false
          }
        ]
      },
      {
        "caption": "Client A clicks Add",
        "hold": 54,
        "burst": false,
        "panes": [
          {
            "img": "wt-collab/LiveSync/p0_02.png",
            "cursor": {
              "x": 834,
              "y": 99
            },
            "click": true
          },
          {
            "img": "wt-collab/LiveSync/p1_02.png",
            "cursor": null,
            "click": false
          }
        ]
      },
      {
        "caption": "Client A adds a card → Client B sees it live",
        "hold": 84,
        "burst": true,
        "panes": [
          {
            "imgs": [
              "wt-collab/LiveSync/p0_03_00.png",
              "wt-collab/LiveSync/p0_03_01.png",
              "wt-collab/LiveSync/p0_03_02.png",
              "wt-collab/LiveSync/p0_03_03.png",
              "wt-collab/LiveSync/p0_03_04.png",
              "wt-collab/LiveSync/p0_03_05.png",
              "wt-collab/LiveSync/p0_03_06.png",
              "wt-collab/LiveSync/p0_03_07.png",
              "wt-collab/LiveSync/p0_03_08.png",
              "wt-collab/LiveSync/p0_03_09.png"
            ],
            "cursor": {
              "x": 834,
              "y": 99
            },
            "click": false
          },
          {
            "imgs": [
              "wt-collab/LiveSync/p1_03_00.png",
              "wt-collab/LiveSync/p1_03_01.png",
              "wt-collab/LiveSync/p1_03_02.png",
              "wt-collab/LiveSync/p1_03_03.png",
              "wt-collab/LiveSync/p1_03_04.png",
              "wt-collab/LiveSync/p1_03_05.png",
              "wt-collab/LiveSync/p1_03_06.png",
              "wt-collab/LiveSync/p1_03_07.png",
              "wt-collab/LiveSync/p1_03_08.png",
              "wt-collab/LiveSync/p1_03_09.png"
            ],
            "cursor": null,
            "click": false
          }
        ]
      },
      {
        "caption": "Synced — both clients agree",
        "hold": 78,
        "burst": false,
        "panes": [
          {
            "img": "wt-collab/LiveSync/p0_04.png",
            "cursor": null,
            "click": false
          },
          {
            "img": "wt-collab/LiveSync/p1_04.png",
            "cursor": null,
            "click": false
          }
        ]
      },
      {
        "caption": "Client A asks the agent to act",
        "hold": 56,
        "burst": false,
        "panes": [
          {
            "img": "wt-collab/LiveSync/p0_05.png",
            "cursor": {
              "x": 937,
              "y": 99
            },
            "click": true
          },
          {
            "img": "wt-collab/LiveSync/p1_05.png",
            "cursor": null,
            "click": false
          }
        ]
      },
      {
        "caption": "Server-led agent streams to every client",
        "hold": 90,
        "burst": true,
        "panes": [
          {
            "imgs": [
              "wt-collab/LiveSync/p0_06_00.png",
              "wt-collab/LiveSync/p0_06_01.png",
              "wt-collab/LiveSync/p0_06_02.png",
              "wt-collab/LiveSync/p0_06_03.png",
              "wt-collab/LiveSync/p0_06_04.png",
              "wt-collab/LiveSync/p0_06_05.png",
              "wt-collab/LiveSync/p0_06_06.png",
              "wt-collab/LiveSync/p0_06_07.png",
              "wt-collab/LiveSync/p0_06_08.png",
              "wt-collab/LiveSync/p0_06_09.png",
              "wt-collab/LiveSync/p0_06_10.png"
            ],
            "cursor": {
              "x": 937,
              "y": 99
            },
            "click": false
          },
          {
            "imgs": [
              "wt-collab/LiveSync/p1_06_00.png",
              "wt-collab/LiveSync/p1_06_01.png",
              "wt-collab/LiveSync/p1_06_02.png",
              "wt-collab/LiveSync/p1_06_03.png",
              "wt-collab/LiveSync/p1_06_04.png",
              "wt-collab/LiveSync/p1_06_05.png",
              "wt-collab/LiveSync/p1_06_06.png",
              "wt-collab/LiveSync/p1_06_07.png",
              "wt-collab/LiveSync/p1_06_08.png",
              "wt-collab/LiveSync/p1_06_09.png",
              "wt-collab/LiveSync/p1_06_10.png"
            ],
            "cursor": null,
            "click": false
          }
        ]
      },
      {
        "caption": "Every client converges on the same state",
        "hold": 96,
        "burst": false,
        "panes": [
          {
            "img": "wt-collab/LiveSync/p0_07.png",
            "cursor": null,
            "click": false
          },
          {
            "img": "wt-collab/LiveSync/p1_07.png",
            "cursor": null,
            "click": false
          }
        ]
      }
    ]
  },
  {
    "id": "LiveSync3",
    "title": "Live Collaboration · 3 clients",
    "accent": "#34d399",
    "vw": 1280,
    "vh": 600,
    "cropVH": 360,
    "paneLabels": [
      "Client A",
      "Client B",
      "Client C"
    ],
    "steps": [
      {
        "caption": "Three clients, one shared board",
        "hold": 66,
        "burst": false,
        "panes": [
          {
            "img": "wt-collab/LiveSync3/p0_00.png",
            "cursor": null,
            "click": false
          },
          {
            "img": "wt-collab/LiveSync3/p1_00.png",
            "cursor": null,
            "click": false
          },
          {
            "img": "wt-collab/LiveSync3/p2_00.png",
            "cursor": null,
            "click": false
          }
        ]
      },
      {
        "caption": "Client A composes a card",
        "hold": 54,
        "burst": false,
        "panes": [
          {
            "img": "wt-collab/LiveSync3/p0_01.png",
            "cursor": {
              "x": 537,
              "y": 99
            },
            "click": false
          },
          {
            "img": "wt-collab/LiveSync3/p1_01.png",
            "cursor": null,
            "click": false
          },
          {
            "img": "wt-collab/LiveSync3/p2_01.png",
            "cursor": null,
            "click": false
          }
        ]
      },
      {
        "caption": "Client A clicks Add",
        "hold": 52,
        "burst": false,
        "panes": [
          {
            "img": "wt-collab/LiveSync3/p0_02.png",
            "cursor": {
              "x": 834,
              "y": 99
            },
            "click": true
          },
          {
            "img": "wt-collab/LiveSync3/p1_02.png",
            "cursor": null,
            "click": false
          },
          {
            "img": "wt-collab/LiveSync3/p2_02.png",
            "cursor": null,
            "click": false
          }
        ]
      },
      {
        "caption": "One add → B and C both update live",
        "hold": 86,
        "burst": true,
        "panes": [
          {
            "imgs": [
              "wt-collab/LiveSync3/p0_03_00.png",
              "wt-collab/LiveSync3/p0_03_01.png",
              "wt-collab/LiveSync3/p0_03_02.png",
              "wt-collab/LiveSync3/p0_03_03.png",
              "wt-collab/LiveSync3/p0_03_04.png",
              "wt-collab/LiveSync3/p0_03_05.png",
              "wt-collab/LiveSync3/p0_03_06.png",
              "wt-collab/LiveSync3/p0_03_07.png",
              "wt-collab/LiveSync3/p0_03_08.png",
              "wt-collab/LiveSync3/p0_03_09.png"
            ],
            "cursor": {
              "x": 834,
              "y": 99
            },
            "click": false
          },
          {
            "imgs": [
              "wt-collab/LiveSync3/p1_03_00.png",
              "wt-collab/LiveSync3/p1_03_01.png",
              "wt-collab/LiveSync3/p1_03_02.png",
              "wt-collab/LiveSync3/p1_03_03.png",
              "wt-collab/LiveSync3/p1_03_04.png",
              "wt-collab/LiveSync3/p1_03_05.png",
              "wt-collab/LiveSync3/p1_03_06.png",
              "wt-collab/LiveSync3/p1_03_07.png",
              "wt-collab/LiveSync3/p1_03_08.png",
              "wt-collab/LiveSync3/p1_03_09.png"
            ],
            "cursor": null,
            "click": false
          },
          {
            "imgs": [
              "wt-collab/LiveSync3/p2_03_00.png",
              "wt-collab/LiveSync3/p2_03_01.png",
              "wt-collab/LiveSync3/p2_03_02.png",
              "wt-collab/LiveSync3/p2_03_03.png",
              "wt-collab/LiveSync3/p2_03_04.png",
              "wt-collab/LiveSync3/p2_03_05.png",
              "wt-collab/LiveSync3/p2_03_06.png",
              "wt-collab/LiveSync3/p2_03_07.png",
              "wt-collab/LiveSync3/p2_03_08.png",
              "wt-collab/LiveSync3/p2_03_09.png"
            ],
            "cursor": null,
            "click": false
          }
        ]
      },
      {
        "caption": "All three converge — no refresh",
        "hold": 74,
        "burst": false,
        "panes": [
          {
            "img": "wt-collab/LiveSync3/p0_04.png",
            "cursor": null,
            "click": false
          },
          {
            "img": "wt-collab/LiveSync3/p1_04.png",
            "cursor": null,
            "click": false
          },
          {
            "img": "wt-collab/LiveSync3/p2_04.png",
            "cursor": null,
            "click": false
          }
        ]
      },
      {
        "caption": "Client A runs the agent",
        "hold": 54,
        "burst": false,
        "panes": [
          {
            "img": "wt-collab/LiveSync3/p0_05.png",
            "cursor": {
              "x": 937,
              "y": 99
            },
            "click": true
          },
          {
            "img": "wt-collab/LiveSync3/p1_05.png",
            "cursor": null,
            "click": false
          },
          {
            "img": "wt-collab/LiveSync3/p2_05.png",
            "cursor": null,
            "click": false
          }
        ]
      },
      {
        "caption": "Server-led agent streams to all three",
        "hold": 92,
        "burst": true,
        "panes": [
          {
            "imgs": [
              "wt-collab/LiveSync3/p0_06_00.png",
              "wt-collab/LiveSync3/p0_06_01.png",
              "wt-collab/LiveSync3/p0_06_02.png",
              "wt-collab/LiveSync3/p0_06_03.png",
              "wt-collab/LiveSync3/p0_06_04.png",
              "wt-collab/LiveSync3/p0_06_05.png",
              "wt-collab/LiveSync3/p0_06_06.png",
              "wt-collab/LiveSync3/p0_06_07.png",
              "wt-collab/LiveSync3/p0_06_08.png",
              "wt-collab/LiveSync3/p0_06_09.png",
              "wt-collab/LiveSync3/p0_06_10.png"
            ],
            "cursor": {
              "x": 937,
              "y": 99
            },
            "click": false
          },
          {
            "imgs": [
              "wt-collab/LiveSync3/p1_06_00.png",
              "wt-collab/LiveSync3/p1_06_01.png",
              "wt-collab/LiveSync3/p1_06_02.png",
              "wt-collab/LiveSync3/p1_06_03.png",
              "wt-collab/LiveSync3/p1_06_04.png",
              "wt-collab/LiveSync3/p1_06_05.png",
              "wt-collab/LiveSync3/p1_06_06.png",
              "wt-collab/LiveSync3/p1_06_07.png",
              "wt-collab/LiveSync3/p1_06_08.png",
              "wt-collab/LiveSync3/p1_06_09.png",
              "wt-collab/LiveSync3/p1_06_10.png"
            ],
            "cursor": null,
            "click": false
          },
          {
            "imgs": [
              "wt-collab/LiveSync3/p2_06_00.png",
              "wt-collab/LiveSync3/p2_06_01.png",
              "wt-collab/LiveSync3/p2_06_02.png",
              "wt-collab/LiveSync3/p2_06_03.png",
              "wt-collab/LiveSync3/p2_06_04.png",
              "wt-collab/LiveSync3/p2_06_05.png",
              "wt-collab/LiveSync3/p2_06_06.png",
              "wt-collab/LiveSync3/p2_06_07.png",
              "wt-collab/LiveSync3/p2_06_08.png",
              "wt-collab/LiveSync3/p2_06_09.png",
              "wt-collab/LiveSync3/p2_06_10.png"
            ],
            "cursor": null,
            "click": false
          }
        ]
      },
      {
        "caption": "Every client sees the same final state",
        "hold": 92,
        "burst": false,
        "panes": [
          {
            "img": "wt-collab/LiveSync3/p0_07.png",
            "cursor": null,
            "click": false
          },
          {
            "img": "wt-collab/LiveSync3/p1_07.png",
            "cursor": null,
            "click": false
          },
          {
            "img": "wt-collab/LiveSync3/p2_07.png",
            "cursor": null,
            "click": false
          }
        ]
      }
    ]
  },
  {
    "id": "NRsolo",
    "title": "NodeRoom · human + agent, no clobber",
    "accent": "#8b5cf6",
    "vw": 1280,
    "vh": 800,
    "cropVH": null,
    "paneLabels": [
      "NodeRoom — memory mode (offline, deterministic)"
    ],
    "steps": [
      {
        "caption": "A shared room — humans + a NodeAgent on one spreadsheet",
        "hold": 80,
        "burst": false,
        "panes": [
          {
            "img": "wt-collab/NRsolo/p0_00.png",
            "cursor": null,
            "click": false
          }
        ]
      },
      {
        "caption": "Run collaboration — a human and the agent edit at once",
        "hold": 58,
        "burst": false,
        "panes": [
          {
            "img": "wt-collab/NRsolo/p0_01.png",
            "cursor": {
              "x": 839,
              "y": 169
            },
            "click": true
          }
        ]
      },
      {
        "caption": "The agent locks a cell, drafts, then smart-merges — no clobber",
        "hold": 100,
        "burst": true,
        "panes": [
          {
            "imgs": [
              "wt-collab/NRsolo/p0_02_00.png",
              "wt-collab/NRsolo/p0_02_01.png",
              "wt-collab/NRsolo/p0_02_02.png",
              "wt-collab/NRsolo/p0_02_03.png",
              "wt-collab/NRsolo/p0_02_04.png",
              "wt-collab/NRsolo/p0_02_05.png",
              "wt-collab/NRsolo/p0_02_06.png",
              "wt-collab/NRsolo/p0_02_07.png",
              "wt-collab/NRsolo/p0_02_08.png",
              "wt-collab/NRsolo/p0_02_09.png",
              "wt-collab/NRsolo/p0_02_10.png",
              "wt-collab/NRsolo/p0_02_11.png",
              "wt-collab/NRsolo/p0_02_12.png"
            ],
            "cursor": {
              "x": 870,
              "y": 160
            },
            "click": false
          }
        ]
      },
      {
        "caption": "Every change — human or agent — lands in the audit trace",
        "hold": 92,
        "burst": false,
        "panes": [
          {
            "img": "wt-collab/NRsolo/p0_03.png",
            "cursor": null,
            "click": false
          }
        ]
      }
    ]
  },
  {
    "id": "NRsync",
    "title": "NodeRoom · live sync + a server-led agent",
    "accent": "#34d399",
    "vw": 1280,
    "vh": 800,
    "cropVH": null,
    "paneLabels": [
      "Client A",
      "Client B"
    ],
    "steps": [
      {
        "caption": "Two clients, one shared NodeRoom",
        "hold": 74,
        "burst": false,
        "zoomScale": null,
        "panes": [
          {
            "img": "wt-collab/NRsync/p0_00.png",
            "cursor": null,
            "click": false,
            "zoom": null
          },
          {
            "img": "wt-collab/NRsync/p1_00.png",
            "cursor": null,
            "click": false,
            "zoom": null
          }
        ]
      },
      {
        "caption": "Client A sends a message",
        "hold": 50,
        "burst": false,
        "zoomScale": null,
        "panes": [
          {
            "img": "wt-collab/NRsync/p0_01.png",
            "cursor": {
              "x": 518,
              "y": 677
            },
            "click": true,
            "zoom": null
          },
          {
            "img": "wt-collab/NRsync/p1_01.png",
            "cursor": null,
            "click": false,
            "zoom": null
          }
        ]
      },
      {
        "caption": "It lands in Client B instantly — no refresh",
        "hold": 88,
        "burst": true,
        "zoomScale": 1.65,
        "panes": [
          {
            "imgs": [
              "wt-collab/NRsync/p0_02_00.png",
              "wt-collab/NRsync/p0_02_01.png",
              "wt-collab/NRsync/p0_02_02.png",
              "wt-collab/NRsync/p0_02_03.png",
              "wt-collab/NRsync/p0_02_04.png",
              "wt-collab/NRsync/p0_02_05.png",
              "wt-collab/NRsync/p0_02_06.png",
              "wt-collab/NRsync/p0_02_07.png",
              "wt-collab/NRsync/p0_02_08.png",
              "wt-collab/NRsync/p0_02_09.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 406,
              "y": 385
            }
          },
          {
            "imgs": [
              "wt-collab/NRsync/p1_02_00.png",
              "wt-collab/NRsync/p1_02_01.png",
              "wt-collab/NRsync/p1_02_02.png",
              "wt-collab/NRsync/p1_02_03.png",
              "wt-collab/NRsync/p1_02_04.png",
              "wt-collab/NRsync/p1_02_05.png",
              "wt-collab/NRsync/p1_02_06.png",
              "wt-collab/NRsync/p1_02_07.png",
              "wt-collab/NRsync/p1_02_08.png",
              "wt-collab/NRsync/p1_02_09.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 406,
              "y": 389
            }
          }
        ]
      },
      {
        "caption": "Client A asks the Room NodeAgent to reconcile Q3",
        "hold": 54,
        "burst": false,
        "zoomScale": 1.65,
        "panes": [
          {
            "img": "wt-collab/NRsync/p0_03.png",
            "cursor": {
              "x": 518,
              "y": 677
            },
            "click": true,
            "zoom": {
              "x": 406,
              "y": 389
            }
          },
          {
            "img": "wt-collab/NRsync/p1_03.png",
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 406,
              "y": 389
            }
          }
        ]
      },
      {
        "caption": "The agent locks cells and fills the variance — live, on BOTH clients",
        "hold": 120,
        "burst": true,
        "zoomScale": 1.6,
        "panes": [
          {
            "imgs": [
              "wt-collab/NRsync/p0_04_00.png",
              "wt-collab/NRsync/p0_04_01.png",
              "wt-collab/NRsync/p0_04_02.png",
              "wt-collab/NRsync/p0_04_03.png",
              "wt-collab/NRsync/p0_04_04.png",
              "wt-collab/NRsync/p0_04_05.png",
              "wt-collab/NRsync/p0_04_06.png",
              "wt-collab/NRsync/p0_04_07.png",
              "wt-collab/NRsync/p0_04_08.png",
              "wt-collab/NRsync/p0_04_09.png",
              "wt-collab/NRsync/p0_04_10.png",
              "wt-collab/NRsync/p0_04_11.png",
              "wt-collab/NRsync/p0_04_12.png",
              "wt-collab/NRsync/p0_04_13.png",
              "wt-collab/NRsync/p0_04_14.png",
              "wt-collab/NRsync/p0_04_15.png",
              "wt-collab/NRsync/p0_04_16.png",
              "wt-collab/NRsync/p0_04_17.png",
              "wt-collab/NRsync/p0_04_18.png",
              "wt-collab/NRsync/p0_04_19.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 753,
              "y": 426
            }
          },
          {
            "imgs": [
              "wt-collab/NRsync/p1_04_00.png",
              "wt-collab/NRsync/p1_04_01.png",
              "wt-collab/NRsync/p1_04_02.png",
              "wt-collab/NRsync/p1_04_03.png",
              "wt-collab/NRsync/p1_04_04.png",
              "wt-collab/NRsync/p1_04_05.png",
              "wt-collab/NRsync/p1_04_06.png",
              "wt-collab/NRsync/p1_04_07.png",
              "wt-collab/NRsync/p1_04_08.png",
              "wt-collab/NRsync/p1_04_09.png",
              "wt-collab/NRsync/p1_04_10.png",
              "wt-collab/NRsync/p1_04_11.png",
              "wt-collab/NRsync/p1_04_12.png",
              "wt-collab/NRsync/p1_04_13.png",
              "wt-collab/NRsync/p1_04_14.png",
              "wt-collab/NRsync/p1_04_15.png",
              "wt-collab/NRsync/p1_04_16.png",
              "wt-collab/NRsync/p1_04_17.png",
              "wt-collab/NRsync/p1_04_18.png",
              "wt-collab/NRsync/p1_04_19.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 753,
              "y": 426
            }
          }
        ]
      },
      {
        "caption": "One server-led agent, broadcast to every client",
        "hold": 90,
        "burst": false,
        "zoomScale": 1.6,
        "panes": [
          {
            "img": "wt-collab/NRsync/p0_05.png",
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 753,
              "y": 426
            }
          },
          {
            "img": "wt-collab/NRsync/p1_05.png",
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 753,
              "y": 426
            }
          }
        ]
      }
    ]
  },
  {
    "id": "NRfresh",
    "title": "NodeRoom · a fresh room, reconciled by the agent",
    "accent": "#f59e0b",
    "vw": 1280,
    "vh": 800,
    "cropVH": null,
    "paneLabels": [
      "Client A (host)",
      "Client B"
    ],
    "steps": [
      {
        "caption": "A brand-new room — two clients, a fresh Q3 sheet",
        "hold": 76,
        "burst": false,
        "zoomScale": null,
        "panes": [
          {
            "img": "wt-collab/NRfresh/p0_00.png",
            "cursor": null,
            "click": false,
            "zoom": null
          },
          {
            "img": "wt-collab/NRfresh/p1_00.png",
            "cursor": null,
            "click": false,
            "zoom": null
          }
        ]
      },
      {
        "caption": "The variance column starts empty",
        "hold": 84,
        "burst": false,
        "zoomScale": 1.55,
        "panes": [
          {
            "img": "wt-collab/NRfresh/p0_01.png",
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 753,
              "y": 426
            }
          },
          {
            "img": "wt-collab/NRfresh/p1_01.png",
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 753,
              "y": 426
            }
          }
        ]
      },
      {
        "caption": "Client A asks the Room NodeAgent to reconcile",
        "hold": 54,
        "burst": false,
        "zoomScale": 1.65,
        "panes": [
          {
            "img": "wt-collab/NRfresh/p0_02.png",
            "cursor": {
              "x": 518,
              "y": 677
            },
            "click": true,
            "zoom": {
              "x": 406,
              "y": 372
            }
          },
          {
            "img": "wt-collab/NRfresh/p1_02.png",
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 406,
              "y": 372
            }
          }
        ]
      },
      {
        "caption": "The agent fills the empty variance — live, on BOTH clients",
        "hold": 130,
        "burst": true,
        "zoomScale": 1.55,
        "panes": [
          {
            "imgs": [
              "wt-collab/NRfresh/p0_03_00.png",
              "wt-collab/NRfresh/p0_03_01.png",
              "wt-collab/NRfresh/p0_03_02.png",
              "wt-collab/NRfresh/p0_03_03.png",
              "wt-collab/NRfresh/p0_03_04.png",
              "wt-collab/NRfresh/p0_03_05.png",
              "wt-collab/NRfresh/p0_03_06.png",
              "wt-collab/NRfresh/p0_03_07.png",
              "wt-collab/NRfresh/p0_03_08.png",
              "wt-collab/NRfresh/p0_03_09.png",
              "wt-collab/NRfresh/p0_03_10.png",
              "wt-collab/NRfresh/p0_03_11.png",
              "wt-collab/NRfresh/p0_03_12.png",
              "wt-collab/NRfresh/p0_03_13.png",
              "wt-collab/NRfresh/p0_03_14.png",
              "wt-collab/NRfresh/p0_03_15.png",
              "wt-collab/NRfresh/p0_03_16.png",
              "wt-collab/NRfresh/p0_03_17.png",
              "wt-collab/NRfresh/p0_03_18.png",
              "wt-collab/NRfresh/p0_03_19.png",
              "wt-collab/NRfresh/p0_03_20.png",
              "wt-collab/NRfresh/p0_03_21.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 753,
              "y": 426
            }
          },
          {
            "imgs": [
              "wt-collab/NRfresh/p1_03_00.png",
              "wt-collab/NRfresh/p1_03_01.png",
              "wt-collab/NRfresh/p1_03_02.png",
              "wt-collab/NRfresh/p1_03_03.png",
              "wt-collab/NRfresh/p1_03_04.png",
              "wt-collab/NRfresh/p1_03_05.png",
              "wt-collab/NRfresh/p1_03_06.png",
              "wt-collab/NRfresh/p1_03_07.png",
              "wt-collab/NRfresh/p1_03_08.png",
              "wt-collab/NRfresh/p1_03_09.png",
              "wt-collab/NRfresh/p1_03_10.png",
              "wt-collab/NRfresh/p1_03_11.png",
              "wt-collab/NRfresh/p1_03_12.png",
              "wt-collab/NRfresh/p1_03_13.png",
              "wt-collab/NRfresh/p1_03_14.png",
              "wt-collab/NRfresh/p1_03_15.png",
              "wt-collab/NRfresh/p1_03_16.png",
              "wt-collab/NRfresh/p1_03_17.png",
              "wt-collab/NRfresh/p1_03_18.png",
              "wt-collab/NRfresh/p1_03_19.png",
              "wt-collab/NRfresh/p1_03_20.png",
              "wt-collab/NRfresh/p1_03_21.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 753,
              "y": 426
            }
          }
        ]
      },
      {
        "caption": "Empty → reconciled, broadcast to every client",
        "hold": 94,
        "burst": false,
        "zoomScale": 1.55,
        "panes": [
          {
            "img": "wt-collab/NRfresh/p0_04.png",
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 753,
              "y": 426
            }
          },
          {
            "img": "wt-collab/NRfresh/p1_04.png",
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 753,
              "y": 426
            }
          }
        ]
      }
    ]
  },
  {
    "id": "NRdeepDive",
    "title": "NodeRoom · deep-dive fan-out: events, people & contacts",
    "accent": "#f97316",
    "vw": 1280,
    "vh": 800,
    "cropVH": null,
    "paneLabels": [
      "NodeRoom — live dev room with enriched companies"
    ],
    "steps": [
      {
        "caption": "Enriched companies — research complete, ready for deep dive",
        "hold": 90,
        "burst": false,
        "zoomScale": 1.4,
        "panes": [
          {
            "img": "wt-collab/NRdeepDive/p0_00.png",
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 539,
              "y": 382
            }
          }
        ]
      },
      {
        "caption": "Ask the agent to deep-dive a completed company",
        "hold": 56,
        "burst": false,
        "zoomScale": 1.5,
        "panes": [
          {
            "img": "wt-collab/NRdeepDive/p0_01.png",
            "cursor": {
              "x": 1230,
              "y": 588
            },
            "click": true,
            "zoom": {
              "x": 1100,
              "y": 351
            }
          }
        ]
      },
      {
        "caption": "The agent researches events, founders, and possible contacts",
        "hold": 140,
        "burst": true,
        "zoomScale": 1.5,
        "panes": [
          {
            "imgs": [
              "wt-collab/NRdeepDive/p0_02_00.png",
              "wt-collab/NRdeepDive/p0_02_01.png",
              "wt-collab/NRdeepDive/p0_02_02.png",
              "wt-collab/NRdeepDive/p0_02_03.png",
              "wt-collab/NRdeepDive/p0_02_04.png",
              "wt-collab/NRdeepDive/p0_02_05.png",
              "wt-collab/NRdeepDive/p0_02_06.png",
              "wt-collab/NRdeepDive/p0_02_07.png",
              "wt-collab/NRdeepDive/p0_02_08.png",
              "wt-collab/NRdeepDive/p0_02_09.png",
              "wt-collab/NRdeepDive/p0_02_10.png",
              "wt-collab/NRdeepDive/p0_02_11.png",
              "wt-collab/NRdeepDive/p0_02_12.png",
              "wt-collab/NRdeepDive/p0_02_13.png",
              "wt-collab/NRdeepDive/p0_02_14.png",
              "wt-collab/NRdeepDive/p0_02_15.png",
              "wt-collab/NRdeepDive/p0_02_16.png",
              "wt-collab/NRdeepDive/p0_02_17.png",
              "wt-collab/NRdeepDive/p0_02_18.png",
              "wt-collab/NRdeepDive/p0_02_19.png",
              "wt-collab/NRdeepDive/p0_02_20.png",
              "wt-collab/NRdeepDive/p0_02_21.png",
              "wt-collab/NRdeepDive/p0_02_22.png",
              "wt-collab/NRdeepDive/p0_02_23.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 1100,
              "y": 351
            }
          }
        ]
      },
      {
        "caption": "Deep-dive columns: team background, events, founder profiles, contacts",
        "hold": 100,
        "burst": false,
        "zoomScale": 1.45,
        "panes": [
          {
            "img": "wt-collab/NRdeepDive/p0_03.png",
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 539,
              "y": 382
            }
          }
        ]
      },
      {
        "caption": "Per-founder research, outreach topics, and possible contacts — all source-backed",
        "hold": 94,
        "burst": false,
        "zoomScale": 1.4,
        "panes": [
          {
            "img": "wt-collab/NRdeepDive/p0_04.png",
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 539,
              "y": 382
            }
          }
        ]
      }
    ]
  }
];
