// AUTO-GENERATED by walkthrough.solo-founder.mjs — do not edit by hand.
export const WALKTHROUGHS = [
  {
    "id": "SoloFounder",
    "title": "Solo Founder · 3D Proof Run",
    "accent": "#8b5cf6",
    "steps": [
      {
        "img": "wt/SoloFounder/00.png",
        "caption": "Builder console — 3D Research Forge",
        "cursor": null,
        "click": false,
        "hold": 80
      },
      {
        "img": "wt/SoloFounder/01.png",
        "caption": "Switch to ScrollStory Agent",
        "cursor": {
          "x": 214,
          "y": 159
        },
        "click": true,
        "hold": 60
      },
      {
        "img": "wt/SoloFounder/02.png",
        "caption": "Generate a scroll-driven 3D product story",
        "cursor": {
          "x": 150,
          "y": 759
        },
        "click": true,
        "hold": 60
      },
      {
        "imgs": [
          "wt/SoloFounder/03_00.png",
          "wt/SoloFounder/03_01.png",
          "wt/SoloFounder/03_02.png",
          "wt/SoloFounder/03_03.png",
          "wt/SoloFounder/03_04.png"
        ],
        "caption": "3D scroll story generated — with proof gates",
        "cursor": null,
        "click": false,
        "hold": 100,
        "burst": true
      },
      {
        "img": "wt/SoloFounder/04.png",
        "caption": "Open the customer-facing landing page",
        "cursor": {
          "x": 194,
          "y": 71
        },
        "click": true,
        "hold": 60
      },
      {
        "img": "wt/SoloFounder/05.png",
        "caption": "Customer page — animated brand, 3D viewer, scroll beats",
        "cursor": null,
        "click": false,
        "hold": 100
      },
      {
        "img": "wt/SoloFounder/06.png",
        "caption": "Open the internal proof report",
        "cursor": null,
        "click": false,
        "hold": 60
      },
      {
        "img": "wt/SoloFounder/07.png",
        "caption": "Proof report — 32/33 gates passed, design contract verified",
        "cursor": null,
        "click": false,
        "hold": 120
      }
    ]
  }
];
