// AUTO-GENERATED by walkthrough.visual.mjs - do not edit by hand.
export const VISUAL_WALKTHROUGHS = [
  {
    "id": "VisualLabsFlow",
    "title": "VisualLabs full demo flow",
    "accent": "#f3a05d",
    "steps": [
      {
        "img": "wt/VisualLabsFlow/00.png",
        "caption": "VisualLabs turns trends into shippable image prompts",
        "cursor": {
          "x": 93,
          "y": 471
        },
        "click": false,
        "hold": 72
      },
      {
        "img": "wt/VisualLabsFlow/01.png",
        "caption": "Click into the studio",
        "cursor": {
          "x": 93,
          "y": 471
        },
        "click": true,
        "hold": 48
      },
      {
        "img": "wt/VisualLabsFlow/02.png",
        "caption": "Studio view keeps remix, chat, render, and analytics in one place",
        "cursor": {
          "x": 559,
          "y": 668
        },
        "click": false,
        "hold": 78
      },
      {
        "img": "wt/VisualLabsFlow/03.png",
        "caption": "Ask the agent for a better prompt",
        "cursor": {
          "x": 843,
          "y": 757
        },
        "click": true,
        "hold": 54
      },
      {
        "imgs": [
          "wt/VisualLabsFlow/04_00.png",
          "wt/VisualLabsFlow/04_01.png",
          "wt/VisualLabsFlow/04_02.png",
          "wt/VisualLabsFlow/04_03.png",
          "wt/VisualLabsFlow/04_04.png",
          "wt/VisualLabsFlow/04_05.png",
          "wt/VisualLabsFlow/04_06.png",
          "wt/VisualLabsFlow/04_07.png",
          "wt/VisualLabsFlow/04_08.png",
          "wt/VisualLabsFlow/04_09.png"
        ],
        "caption": "OpenAI agent refines the render prompt",
        "cursor": null,
        "click": false,
        "hold": 88,
        "burst": true
      },
      {
        "img": "wt/VisualLabsFlow/05.png",
        "caption": "The refined prompt becomes the image-render input",
        "cursor": {
          "x": 325,
          "y": 284
        },
        "click": false,
        "hold": 70
      },
      {
        "img": "wt/VisualLabsFlow/06.png",
        "caption": "Generate the image",
        "cursor": {
          "x": 325,
          "y": 284
        },
        "click": true,
        "hold": 52
      },
      {
        "imgs": [
          "wt/VisualLabsFlow/07_00.png",
          "wt/VisualLabsFlow/07_01.png",
          "wt/VisualLabsFlow/07_02.png",
          "wt/VisualLabsFlow/07_03.png",
          "wt/VisualLabsFlow/07_04.png",
          "wt/VisualLabsFlow/07_05.png",
          "wt/VisualLabsFlow/07_06.png",
          "wt/VisualLabsFlow/07_07.png"
        ],
        "caption": "Render request runs through /api/render",
        "cursor": null,
        "click": false,
        "hold": 78,
        "burst": true
      },
      {
        "img": "wt/VisualLabsFlow/08.png",
        "caption": "Good image prompt is saved for the Fastino export loop",
        "cursor": {
          "x": 470,
          "y": 284
        },
        "click": false,
        "hold": 80
      },
      {
        "img": "wt/VisualLabsFlow/09.png",
        "caption": "Prepare a safe post draft",
        "cursor": {
          "x": 470,
          "y": 284
        },
        "click": true,
        "hold": 52
      },
      {
        "img": "wt/VisualLabsFlow/10.png",
        "caption": "Composio publish stays dry-run for the walkthrough",
        "cursor": {
          "x": 607,
          "y": 284
        },
        "click": false,
        "hold": 74
      },
      {
        "img": "wt/VisualLabsFlow/11.png",
        "caption": "Pull live social analytics",
        "cursor": {
          "x": 607,
          "y": 284
        },
        "click": true,
        "hold": 52
      },
      {
        "imgs": [
          "wt/VisualLabsFlow/12_00.png",
          "wt/VisualLabsFlow/12_01.png",
          "wt/VisualLabsFlow/12_02.png",
          "wt/VisualLabsFlow/12_03.png",
          "wt/VisualLabsFlow/12_04.png",
          "wt/VisualLabsFlow/12_05.png",
          "wt/VisualLabsFlow/12_06.png",
          "wt/VisualLabsFlow/12_07.png",
          "wt/VisualLabsFlow/12_08.png",
          "wt/VisualLabsFlow/12_09.png"
        ],
        "caption": "Composio analytics streams back into OpenUI chat",
        "cursor": null,
        "click": false,
        "hold": 84,
        "burst": true
      },
      {
        "img": "wt/VisualLabsFlow/13.png",
        "caption": "Analytics artifact gives the post context",
        "cursor": {
          "x": 1113,
          "y": 693
        },
        "click": false,
        "hold": 82
      },
      {
        "img": "wt/VisualLabsFlow/14.png",
        "caption": "Export chat and render history for Fastino",
        "cursor": {
          "x": 1113,
          "y": 693
        },
        "click": true,
        "hold": 52
      },
      {
        "imgs": [
          "wt/VisualLabsFlow/15_00.png",
          "wt/VisualLabsFlow/15_01.png",
          "wt/VisualLabsFlow/15_02.png",
          "wt/VisualLabsFlow/15_03.png",
          "wt/VisualLabsFlow/15_04.png",
          "wt/VisualLabsFlow/15_05.png",
          "wt/VisualLabsFlow/15_06.png",
          "wt/VisualLabsFlow/15_07.png"
        ],
        "caption": "ClickHouse history becomes Fastino-ready training data",
        "cursor": null,
        "click": false,
        "hold": 86,
        "burst": true
      },
      {
        "img": "wt/VisualLabsFlow/16.png",
        "caption": "Training export behavior is visible and mock-safe",
        "cursor": null,
        "click": false,
        "hold": 104
      }
    ]
  }
];
