// AUTO-GENERATED by walkthrough.roomos.mjs - do not edit by hand.
export const ROOMOS_WALKTHROUGHS = [
  {
    "id": "RoomOSV0123",
    "title": "Room OS V0 -> V3",
    "accent": "#8b5cf6",
    "vw": 1280,
    "vh": 720,
    "paneLabels": [
      "V0 Failure",
      "V1 Room State",
      "V2 Work Room",
      "V3 Agent OS"
    ],
    "paneNotes": [
      "raw transcript",
      "shared reducer",
      "typed intent",
      "goal graph"
    ],
    "steps": [
      {
        "caption": "Four fresh production rooms, one per agent version",
        "detail": "Each pane is a real room on room-os-live.vercel.app. Same starting goal, different coordination layer.",
        "hold": 92,
        "burst": false,
        "panes": [
          {
            "imgs": [],
            "img": "wt-roomos/RoomOSV0123/v0_00.png",
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 620,
              "y": 205,
              "scale": 1.16
            },
            "prevCursor": null,
            "prevZoom": null,
            "active": false
          },
          {
            "imgs": [],
            "img": "wt-roomos/RoomOSV0123/v1_00.png",
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 620,
              "y": 205,
              "scale": 1.16
            },
            "prevCursor": null,
            "prevZoom": null,
            "active": false
          },
          {
            "imgs": [],
            "img": "wt-roomos/RoomOSV0123/v2_00.png",
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 620,
              "y": 205,
              "scale": 1.16
            },
            "prevCursor": null,
            "prevZoom": null,
            "active": false
          },
          {
            "imgs": [],
            "img": "wt-roomos/RoomOSV0123/v3_00.png",
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 620,
              "y": 205,
              "scale": 1.16
            },
            "prevCursor": null,
            "prevZoom": null,
            "active": false
          }
        ]
      },
      {
        "caption": "Start the same planning task in every version",
        "detail": "V0 hears transcript only. V1 owns floor/count state. V2 routes interrupts. V3 also exposes goals, workers, artifacts, cost, and latency.",
        "hold": 76,
        "burst": false,
        "panes": [
          {
            "imgs": [],
            "img": "wt-roomos/RoomOSV0123/v0_01.png",
            "cursor": {
              "x": 308,
              "y": 679
            },
            "click": true,
            "zoom": null,
            "prevCursor": null,
            "prevZoom": {
              "x": 620,
              "y": 205,
              "scale": 1.16
            },
            "active": true
          },
          {
            "imgs": [],
            "img": "wt-roomos/RoomOSV0123/v1_01.png",
            "cursor": {
              "x": 308,
              "y": 679
            },
            "click": true,
            "zoom": null,
            "prevCursor": null,
            "prevZoom": {
              "x": 620,
              "y": 205,
              "scale": 1.16
            },
            "active": true
          },
          {
            "imgs": [],
            "img": "wt-roomos/RoomOSV0123/v2_01.png",
            "cursor": {
              "x": 308,
              "y": 679
            },
            "click": true,
            "zoom": null,
            "prevCursor": null,
            "prevZoom": {
              "x": 620,
              "y": 205,
              "scale": 1.16
            },
            "active": true
          },
          {
            "imgs": [],
            "img": "wt-roomos/RoomOSV0123/v3_01.png",
            "cursor": {
              "x": 308,
              "y": 681
            },
            "click": true,
            "zoom": null,
            "prevCursor": null,
            "prevZoom": {
              "x": 620,
              "y": 205,
              "scale": 1.16
            },
            "active": true
          }
        ]
      },
      {
        "caption": "Live model turns appear; the control surface is already different",
        "detail": "The visible difference is not intelligence. It is what state the system can inspect and commit.",
        "hold": 86,
        "burst": true,
        "panes": [
          {
            "imgs": [
              "wt-roomos/RoomOSV0123/v0_02_00.png",
              "wt-roomos/RoomOSV0123/v0_02_01.png",
              "wt-roomos/RoomOSV0123/v0_02_02.png",
              "wt-roomos/RoomOSV0123/v0_02_03.png",
              "wt-roomos/RoomOSV0123/v0_02_04.png",
              "wt-roomos/RoomOSV0123/v0_02_05.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": null,
            "prevCursor": {
              "x": 308,
              "y": 679
            },
            "prevZoom": {
              "x": 620,
              "y": 205,
              "scale": 1.16
            },
            "active": false
          },
          {
            "imgs": [
              "wt-roomos/RoomOSV0123/v1_02_00.png",
              "wt-roomos/RoomOSV0123/v1_02_01.png",
              "wt-roomos/RoomOSV0123/v1_02_02.png",
              "wt-roomos/RoomOSV0123/v1_02_03.png",
              "wt-roomos/RoomOSV0123/v1_02_04.png",
              "wt-roomos/RoomOSV0123/v1_02_05.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": null,
            "prevCursor": {
              "x": 308,
              "y": 679
            },
            "prevZoom": {
              "x": 620,
              "y": 205,
              "scale": 1.16
            },
            "active": false
          },
          {
            "imgs": [
              "wt-roomos/RoomOSV0123/v2_02_00.png",
              "wt-roomos/RoomOSV0123/v2_02_01.png",
              "wt-roomos/RoomOSV0123/v2_02_02.png",
              "wt-roomos/RoomOSV0123/v2_02_03.png",
              "wt-roomos/RoomOSV0123/v2_02_04.png",
              "wt-roomos/RoomOSV0123/v2_02_05.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": null,
            "prevCursor": {
              "x": 308,
              "y": 679
            },
            "prevZoom": {
              "x": 620,
              "y": 205,
              "scale": 1.16
            },
            "active": false
          },
          {
            "imgs": [
              "wt-roomos/RoomOSV0123/v3_02_00.png",
              "wt-roomos/RoomOSV0123/v3_02_01.png",
              "wt-roomos/RoomOSV0123/v3_02_02.png",
              "wt-roomos/RoomOSV0123/v3_02_03.png",
              "wt-roomos/RoomOSV0123/v3_02_04.png",
              "wt-roomos/RoomOSV0123/v3_02_05.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": null,
            "prevCursor": {
              "x": 308,
              "y": 681
            },
            "prevZoom": {
              "x": 620,
              "y": 205,
              "scale": 1.16
            },
            "active": false
          }
        ]
      },
      {
        "caption": "Interrupt all rooms: switch from trip planning to counting",
        "detail": "This is the failure case: the human changes the mission mid-run and expects the room to stay coherent.",
        "hold": 86,
        "burst": false,
        "panes": [
          {
            "imgs": [],
            "img": "wt-roomos/RoomOSV0123/v0_03.png",
            "cursor": {
              "x": 953,
              "y": 679
            },
            "click": true,
            "zoom": null,
            "prevCursor": {
              "x": 308,
              "y": 679
            },
            "prevZoom": {
              "x": 620,
              "y": 205,
              "scale": 1.16
            },
            "active": true
          },
          {
            "imgs": [],
            "img": "wt-roomos/RoomOSV0123/v1_03.png",
            "cursor": {
              "x": 953,
              "y": 679
            },
            "click": true,
            "zoom": null,
            "prevCursor": {
              "x": 308,
              "y": 679
            },
            "prevZoom": {
              "x": 620,
              "y": 205,
              "scale": 1.16
            },
            "active": true
          },
          {
            "imgs": [],
            "img": "wt-roomos/RoomOSV0123/v2_03.png",
            "cursor": {
              "x": 953,
              "y": 679
            },
            "click": true,
            "zoom": null,
            "prevCursor": {
              "x": 308,
              "y": 679
            },
            "prevZoom": {
              "x": 620,
              "y": 205,
              "scale": 1.16
            },
            "active": true
          },
          {
            "imgs": [],
            "img": "wt-roomos/RoomOSV0123/v3_03.png",
            "cursor": {
              "x": 953,
              "y": 702
            },
            "click": true,
            "zoom": null,
            "prevCursor": {
              "x": 308,
              "y": 681
            },
            "prevZoom": {
              "x": 620,
              "y": 205,
              "scale": 1.16
            },
            "active": true
          }
        ]
      },
      {
        "caption": "Reducer-owned state is what makes the steer durable",
        "detail": "V1/V2/V3 can expose turn, floor, count, done, and loop-risk state. V0 can only hope the next model reply remembers.",
        "hold": 96,
        "burst": true,
        "panes": [
          {
            "imgs": [
              "wt-roomos/RoomOSV0123/v0_04_00.png",
              "wt-roomos/RoomOSV0123/v0_04_01.png",
              "wt-roomos/RoomOSV0123/v0_04_02.png",
              "wt-roomos/RoomOSV0123/v0_04_03.png",
              "wt-roomos/RoomOSV0123/v0_04_04.png",
              "wt-roomos/RoomOSV0123/v0_04_05.png",
              "wt-roomos/RoomOSV0123/v0_04_06.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 650,
              "y": 118,
              "scale": 1.42
            },
            "prevCursor": {
              "x": 953,
              "y": 679
            },
            "prevZoom": {
              "x": 620,
              "y": 205,
              "scale": 1.16
            },
            "active": false
          },
          {
            "imgs": [
              "wt-roomos/RoomOSV0123/v1_04_00.png",
              "wt-roomos/RoomOSV0123/v1_04_01.png",
              "wt-roomos/RoomOSV0123/v1_04_02.png",
              "wt-roomos/RoomOSV0123/v1_04_03.png",
              "wt-roomos/RoomOSV0123/v1_04_04.png",
              "wt-roomos/RoomOSV0123/v1_04_05.png",
              "wt-roomos/RoomOSV0123/v1_04_06.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 650,
              "y": 118,
              "scale": 1.42
            },
            "prevCursor": {
              "x": 953,
              "y": 679
            },
            "prevZoom": {
              "x": 620,
              "y": 205,
              "scale": 1.16
            },
            "active": false
          },
          {
            "imgs": [
              "wt-roomos/RoomOSV0123/v2_04_00.png",
              "wt-roomos/RoomOSV0123/v2_04_01.png",
              "wt-roomos/RoomOSV0123/v2_04_02.png",
              "wt-roomos/RoomOSV0123/v2_04_03.png",
              "wt-roomos/RoomOSV0123/v2_04_04.png",
              "wt-roomos/RoomOSV0123/v2_04_05.png",
              "wt-roomos/RoomOSV0123/v2_04_06.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 650,
              "y": 118,
              "scale": 1.42
            },
            "prevCursor": {
              "x": 953,
              "y": 679
            },
            "prevZoom": {
              "x": 620,
              "y": 205,
              "scale": 1.16
            },
            "active": false
          },
          {
            "imgs": [
              "wt-roomos/RoomOSV0123/v3_04_00.png",
              "wt-roomos/RoomOSV0123/v3_04_01.png",
              "wt-roomos/RoomOSV0123/v3_04_02.png",
              "wt-roomos/RoomOSV0123/v3_04_03.png",
              "wt-roomos/RoomOSV0123/v3_04_04.png",
              "wt-roomos/RoomOSV0123/v3_04_05.png",
              "wt-roomos/RoomOSV0123/v3_04_06.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 650,
              "y": 118,
              "scale": 1.42
            },
            "prevCursor": {
              "x": 953,
              "y": 702
            },
            "prevZoom": {
              "x": 620,
              "y": 205,
              "scale": 1.16
            },
            "active": false
          }
        ]
      },
      {
        "caption": "End-to-end run: compare the room receipts",
        "detail": "The bounded transcript shows latest entries, while the roomState strip keeps the authoritative progress compact.",
        "hold": 96,
        "burst": true,
        "panes": [
          {
            "imgs": [
              "wt-roomos/RoomOSV0123/v0_05_00.png",
              "wt-roomos/RoomOSV0123/v0_05_01.png",
              "wt-roomos/RoomOSV0123/v0_05_02.png",
              "wt-roomos/RoomOSV0123/v0_05_03.png",
              "wt-roomos/RoomOSV0123/v0_05_04.png",
              "wt-roomos/RoomOSV0123/v0_05_05.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 640,
              "y": 360,
              "scale": 1.18
            },
            "prevCursor": {
              "x": 953,
              "y": 679
            },
            "prevZoom": {
              "x": 650,
              "y": 118,
              "scale": 1.42
            },
            "active": false
          },
          {
            "imgs": [
              "wt-roomos/RoomOSV0123/v1_05_00.png",
              "wt-roomos/RoomOSV0123/v1_05_01.png",
              "wt-roomos/RoomOSV0123/v1_05_02.png",
              "wt-roomos/RoomOSV0123/v1_05_03.png",
              "wt-roomos/RoomOSV0123/v1_05_04.png",
              "wt-roomos/RoomOSV0123/v1_05_05.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 640,
              "y": 360,
              "scale": 1.18
            },
            "prevCursor": {
              "x": 953,
              "y": 679
            },
            "prevZoom": {
              "x": 650,
              "y": 118,
              "scale": 1.42
            },
            "active": false
          },
          {
            "imgs": [
              "wt-roomos/RoomOSV0123/v2_05_00.png",
              "wt-roomos/RoomOSV0123/v2_05_01.png",
              "wt-roomos/RoomOSV0123/v2_05_02.png",
              "wt-roomos/RoomOSV0123/v2_05_03.png",
              "wt-roomos/RoomOSV0123/v2_05_04.png",
              "wt-roomos/RoomOSV0123/v2_05_05.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 640,
              "y": 360,
              "scale": 1.18
            },
            "prevCursor": {
              "x": 953,
              "y": 679
            },
            "prevZoom": {
              "x": 650,
              "y": 118,
              "scale": 1.42
            },
            "active": false
          },
          {
            "imgs": [
              "wt-roomos/RoomOSV0123/v3_05_00.png",
              "wt-roomos/RoomOSV0123/v3_05_01.png",
              "wt-roomos/RoomOSV0123/v3_05_02.png",
              "wt-roomos/RoomOSV0123/v3_05_03.png",
              "wt-roomos/RoomOSV0123/v3_05_04.png",
              "wt-roomos/RoomOSV0123/v3_05_05.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 640,
              "y": 360,
              "scale": 1.18
            },
            "prevCursor": {
              "x": 953,
              "y": 702
            },
            "prevZoom": {
              "x": 650,
              "y": 118,
              "scale": 1.42
            },
            "active": false
          }
        ]
      },
      {
        "caption": "Open the internal-state drawer for auditability",
        "detail": "V3 adds the agent-OS layer: policy, goal graph, workers, artifacts, expected cost, observed latency, and trace payloads.",
        "hold": 118,
        "burst": false,
        "panes": [
          {
            "imgs": [],
            "img": "wt-roomos/RoomOSV0123/v0_06.png",
            "cursor": {
              "x": 1147,
              "y": 26
            },
            "click": true,
            "zoom": {
              "x": 133,
              "y": 509,
              "scale": 1.34
            },
            "prevCursor": {
              "x": 953,
              "y": 679
            },
            "prevZoom": {
              "x": 640,
              "y": 360,
              "scale": 1.18
            },
            "active": true
          },
          {
            "imgs": [],
            "img": "wt-roomos/RoomOSV0123/v1_06.png",
            "cursor": {
              "x": 1147,
              "y": 26
            },
            "click": true,
            "zoom": {
              "x": 133,
              "y": 509,
              "scale": 1.34
            },
            "prevCursor": {
              "x": 953,
              "y": 679
            },
            "prevZoom": {
              "x": 640,
              "y": 360,
              "scale": 1.18
            },
            "active": true
          },
          {
            "imgs": [],
            "img": "wt-roomos/RoomOSV0123/v2_06.png",
            "cursor": {
              "x": 1147,
              "y": 26
            },
            "click": true,
            "zoom": {
              "x": 133,
              "y": 509,
              "scale": 1.34
            },
            "prevCursor": {
              "x": 953,
              "y": 679
            },
            "prevZoom": {
              "x": 640,
              "y": 360,
              "scale": 1.18
            },
            "active": true
          },
          {
            "imgs": [],
            "img": "wt-roomos/RoomOSV0123/v3_06.png",
            "cursor": {
              "x": 1147,
              "y": 22
            },
            "click": true,
            "zoom": {
              "x": 335,
              "y": 720,
              "scale": 1.34
            },
            "prevCursor": {
              "x": 953,
              "y": 702
            },
            "prevZoom": {
              "x": 640,
              "y": 360,
              "scale": 1.18
            },
            "active": true
          }
        ]
      }
    ]
  }
];
