// AUTO-GENERATED by demo/walkthrough.mjs — do not edit by hand.
export const WALKTHROUGHS = [
  {
    "id": "ListIntel",
    "title": "List Intelligence",
    "accent": "#10b981",
    "steps": [
      {
        "img": "wt/ListIntel/00.png",
        "caption": "Paste a list of companies",
        "cursor": {
          "x": 448,
          "y": 413
        },
        "click": false,
        "hold": 66
      },
      {
        "img": "wt/ListIntel/01.png",
        "caption": "Click Run pipeline",
        "cursor": {
          "x": 640,
          "y": 517
        },
        "click": true,
        "hold": 60
      },
      {
        "img": "wt/ListIntel/02.png",
        "caption": "MATCH → ENRICH → CLASSIFY → SCORE, live",
        "cursor": null,
        "click": false,
        "hold": 70
      },
      {
        "img": "wt/ListIntel/03.png",
        "caption": "Every company scored — evidence-backed",
        "cursor": null,
        "click": false,
        "hold": 104
      }
    ]
  },
  {
    "id": "Graph",
    "title": "Relationship Graph",
    "accent": "#34d399",
    "steps": [
      {
        "img": "wt/Graph/00.png",
        "caption": "Type a seed company",
        "cursor": {
          "x": 640,
          "y": 370
        },
        "click": false,
        "hold": 60
      },
      {
        "img": "wt/Graph/01.png",
        "caption": "Build the relationship graph",
        "cursor": {
          "x": 153,
          "y": 422
        },
        "click": true,
        "hold": 60
      },
      {
        "img": "wt/Graph/02.png",
        "caption": "Extracting source-backed relationships…",
        "cursor": null,
        "click": false,
        "hold": 64
      },
      {
        "img": "wt/Graph/03.png",
        "caption": "Interactive corporate lineage",
        "cursor": null,
        "click": false,
        "hold": 110
      }
    ]
  },
  {
    "id": "Cards",
    "title": "Card → Rows",
    "accent": "#0A7CFF",
    "steps": [
      {
        "img": "wt/Cards/00.png",
        "caption": "Drop a cap table / deck slide image",
        "cursor": {
          "x": 640,
          "y": 341
        },
        "click": false,
        "hold": 64
      },
      {
        "img": "wt/Cards/01.png",
        "caption": "Extract the companies",
        "cursor": {
          "x": 640,
          "y": 608
        },
        "click": true,
        "hold": 60
      },
      {
        "img": "wt/Cards/02.png",
        "caption": "Gemini reads the image (multimodal)…",
        "cursor": null,
        "click": false,
        "hold": 56
      },
      {
        "img": "wt/Cards/03.png",
        "caption": "Structured rows — ready for List Intelligence",
        "cursor": null,
        "click": false,
        "hold": 104
      }
    ]
  },
  {
    "id": "DocBrain",
    "title": "Document Brain",
    "accent": "#8E75B2",
    "steps": [
      {
        "img": "wt/DocBrain/00.png",
        "caption": "Upload your own documents",
        "cursor": {
          "x": 640,
          "y": 341
        },
        "click": false,
        "hold": 60
      },
      {
        "img": "wt/DocBrain/01.png",
        "caption": "Ingest & index",
        "cursor": {
          "x": 354,
          "y": 416
        },
        "click": true,
        "hold": 56
      },
      {
        "img": "wt/DocBrain/02.png",
        "caption": "Ask a question about your files",
        "cursor": {
          "x": 625,
          "y": 760
        },
        "click": false,
        "hold": 60
      },
      {
        "img": "wt/DocBrain/03.png",
        "caption": "Grounded answer — with (file#chunk) citations",
        "cursor": null,
        "click": false,
        "hold": 110
      }
    ]
  },
  {
    "id": "Ebitda",
    "title": "EBITDA Bridge",
    "accent": "#10b981",
    "steps": [
      {
        "img": "wt/Ebitda/00.png",
        "caption": "Enter the income-statement figures",
        "cursor": {
          "x": 228,
          "y": 400
        },
        "click": false,
        "hold": 64
      },
      {
        "img": "wt/Ebitda/01.png",
        "caption": "…each line — no number is computed by the LLM",
        "cursor": {
          "x": 228,
          "y": 479
        },
        "click": false,
        "hold": 60
      },
      {
        "img": "wt/Ebitda/02.png",
        "caption": "Python computes EBIT → EBITDA → Adjusted EBITDA",
        "cursor": null,
        "click": false,
        "hold": 112
      }
    ]
  }
];
