// AUTO-GENERATED by demo/walkthrough.mjs — do not edit by hand.
export const WALKTHROUGHS = [
  {
    "id": "ListIntel",
    "title": "List Intelligence",
    "accent": "#10b981",
    "steps": [
      {
        "img": "wt/ListIntel/00.png",
        "caption": "Paste a list of companies",
        "cursor": {
          "x": 448,
          "y": 413
        },
        "click": false,
        "hold": 66
      },
      {
        "img": "wt/ListIntel/01.png",
        "caption": "Click Run pipeline",
        "cursor": {
          "x": 640,
          "y": 517
        },
        "click": true,
        "hold": 60
      },
      {
        "imgs": [
          "wt/ListIntel/02_00.png",
          "wt/ListIntel/02_01.png",
          "wt/ListIntel/02_02.png",
          "wt/ListIntel/02_03.png",
          "wt/ListIntel/02_04.png",
          "wt/ListIntel/02_05.png",
          "wt/ListIntel/02_06.png",
          "wt/ListIntel/02_07.png",
          "wt/ListIntel/02_08.png",
          "wt/ListIntel/02_09.png",
          "wt/ListIntel/02_10.png"
        ],
        "caption": "MATCH → ENRICH → CLASSIFY → SCORE — running live",
        "cursor": null,
        "click": false,
        "hold": 78,
        "burst": true
      },
      {
        "img": "wt/ListIntel/03.png",
        "caption": "Every company scored — evidence-backed",
        "cursor": null,
        "click": false,
        "hold": 104
      }
    ]
  },
  {
    "id": "Graph",
    "title": "Relationship Graph",
    "accent": "#34d399",
    "steps": [
      {
        "img": "wt/Graph/00.png",
        "caption": "Type a seed company",
        "cursor": {
          "x": 640,
          "y": 370
        },
        "click": false,
        "hold": 60
      },
      {
        "img": "wt/Graph/01.png",
        "caption": "Build the relationship graph",
        "cursor": {
          "x": 153,
          "y": 422
        },
        "click": true,
        "hold": 60
      },
      {
        "imgs": [
          "wt/Graph/02_00.png",
          "wt/Graph/02_01.png",
          "wt/Graph/02_02.png",
          "wt/Graph/02_03.png",
          "wt/Graph/02_04.png",
          "wt/Graph/02_05.png",
          "wt/Graph/02_06.png",
          "wt/Graph/02_07.png",
          "wt/Graph/02_08.png",
          "wt/Graph/02_09.png"
        ],
        "caption": "Extracting source-backed relationships — live",
        "cursor": null,
        "click": false,
        "hold": 74,
        "burst": true
      },
      {
        "img": "wt/Graph/03.png",
        "caption": "Interactive corporate lineage",
        "cursor": null,
        "click": false,
        "hold": 110
      }
    ]
  },
  {
    "id": "Cards",
    "title": "Card → Rows",
    "accent": "#0A7CFF",
    "steps": [
      {
        "img": "wt/Cards/00.png",
        "caption": "Drop a cap table / deck slide image",
        "cursor": {
          "x": 640,
          "y": 341
        },
        "click": false,
        "hold": 64
      },
      {
        "img": "wt/Cards/01.png",
        "caption": "Extract the companies",
        "cursor": {
          "x": 640,
          "y": 608
        },
        "click": true,
        "hold": 60
      },
      {
        "imgs": [
          "wt/Cards/02_00.png",
          "wt/Cards/02_01.png",
          "wt/Cards/02_02.png",
          "wt/Cards/02_03.png",
          "wt/Cards/02_04.png",
          "wt/Cards/02_05.png",
          "wt/Cards/02_06.png",
          "wt/Cards/02_07.png",
          "wt/Cards/02_08.png"
        ],
        "caption": "Gemini reads the image — multimodal, live",
        "cursor": null,
        "click": false,
        "hold": 66,
        "burst": true
      },
      {
        "img": "wt/Cards/03.png",
        "caption": "Structured rows — ready for List Intelligence",
        "cursor": null,
        "click": false,
        "hold": 104
      }
    ]
  },
  {
    "id": "DocBrain",
    "title": "Document Brain",
    "accent": "#8E75B2",
    "steps": [
      {
        "img": "wt/DocBrain/00.png",
        "caption": "Upload your own documents",
        "cursor": {
          "x": 640,
          "y": 341
        },
        "click": false,
        "hold": 60
      },
      {
        "img": "wt/DocBrain/01.png",
        "caption": "Ingest & index",
        "cursor": {
          "x": 354,
          "y": 416
        },
        "click": true,
        "hold": 56
      },
      {
        "img": "wt/DocBrain/02.png",
        "caption": "Ask a question about your files",
        "cursor": {
          "x": 625,
          "y": 760
        },
        "click": false,
        "hold": 60
      },
      {
        "imgs": [
          "wt/DocBrain/03_00.png",
          "wt/DocBrain/03_01.png",
          "wt/DocBrain/03_02.png",
          "wt/DocBrain/03_03.png",
          "wt/DocBrain/03_04.png",
          "wt/DocBrain/03_05.png",
          "wt/DocBrain/03_06.png",
          "wt/DocBrain/03_07.png",
          "wt/DocBrain/03_08.png"
        ],
        "caption": "Searching your documents — grounded retrieval",
        "cursor": null,
        "click": false,
        "hold": 62,
        "burst": true
      },
      {
        "img": "wt/DocBrain/04.png",
        "caption": "Grounded answer — with (file#chunk) citations",
        "cursor": null,
        "click": false,
        "hold": 110
      }
    ]
  },
  {
    "id": "Ebitda",
    "title": "EBITDA Bridge",
    "accent": "#10b981",
    "steps": [
      {
        "img": "wt/Ebitda/00.png",
        "caption": "Enter the income-statement figures",
        "cursor": {
          "x": 228,
          "y": 400
        },
        "click": false,
        "hold": 64
      },
      {
        "img": "wt/Ebitda/01.png",
        "caption": "…each line — no number is computed by the LLM",
        "cursor": {
          "x": 228,
          "y": 479
        },
        "click": false,
        "hold": 60
      },
      {
        "img": "wt/Ebitda/02.png",
        "caption": "Python computes EBIT → EBITDA → Adjusted EBITDA",
        "cursor": null,
        "click": false,
        "hold": 112
      }
    ]
  }
];
