// AUTO-GENERATED by walkthrough.roomos.mjs - do not edit by hand.
export const ROOMOS_WALKTHROUGHS = [
  {
    "id": "RoomOSV0123",
    "title": "Room OS V0 -> V3",
    "accent": "#8b5cf6",
    "vw": 1280,
    "vh": 720,
    "paneLabels": [
      "V0 Failure",
      "V1 Room State",
      "V2 Work Room",
      "V3 Agent OS"
    ],
    "paneNotes": [
      "raw transcript",
      "shared reducer",
      "typed intent",
      "goal graph"
    ],
    "steps": [
      {
        "caption": "Four fresh production rooms, one per agent version",
        "detail": "Same live task, same model surface, different coordination layer. The QR is hidden so the transcript and state can stay visible.",
        "hold": 88,
        "burst": false,
        "layout": "grid",
        "panes": [
          {
            "imgs": [],
            "img": "wt-roomos/RoomOSV0123/v0_00.png",
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 620,
              "y": 218,
              "scale": 1.18
            },
            "prevCursor": null,
            "prevZoom": null,
            "active": false
          },
          {
            "imgs": [],
            "img": "wt-roomos/RoomOSV0123/v1_00.png",
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 620,
              "y": 218,
              "scale": 1.18
            },
            "prevCursor": null,
            "prevZoom": null,
            "active": false
          },
          {
            "imgs": [],
            "img": "wt-roomos/RoomOSV0123/v2_00.png",
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 620,
              "y": 218,
              "scale": 1.18
            },
            "prevCursor": null,
            "prevZoom": null,
            "active": false
          },
          {
            "imgs": [],
            "img": "wt-roomos/RoomOSV0123/v3_00.png",
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 620,
              "y": 218,
              "scale": 1.18
            },
            "prevCursor": null,
            "prevZoom": null,
            "active": false
          }
        ]
      },
      {
        "caption": "Start the same planning task in every version",
        "detail": "V0 hears transcript only. V1 owns floor/count state. V2 routes interrupts. V3 also exposes goals, workers, artifacts, cost, and latency.",
        "hold": 76,
        "burst": false,
        "layout": "grid",
        "panes": [
          {
            "imgs": [],
            "img": "wt-roomos/RoomOSV0123/v0_01.png",
            "cursor": {
              "x": 308,
              "y": 679
            },
            "click": true,
            "zoom": null,
            "prevCursor": null,
            "prevZoom": {
              "x": 620,
              "y": 218,
              "scale": 1.18
            },
            "active": true
          },
          {
            "imgs": [],
            "img": "wt-roomos/RoomOSV0123/v1_01.png",
            "cursor": {
              "x": 308,
              "y": 679
            },
            "click": true,
            "zoom": null,
            "prevCursor": null,
            "prevZoom": {
              "x": 620,
              "y": 218,
              "scale": 1.18
            },
            "active": true
          },
          {
            "imgs": [],
            "img": "wt-roomos/RoomOSV0123/v2_01.png",
            "cursor": {
              "x": 308,
              "y": 679
            },
            "click": true,
            "zoom": null,
            "prevCursor": null,
            "prevZoom": {
              "x": 620,
              "y": 218,
              "scale": 1.18
            },
            "active": true
          },
          {
            "imgs": [],
            "img": "wt-roomos/RoomOSV0123/v3_01.png",
            "cursor": {
              "x": 308,
              "y": 679
            },
            "click": true,
            "zoom": null,
            "prevCursor": null,
            "prevZoom": {
              "x": 620,
              "y": 218,
              "scale": 1.18
            },
            "active": true
          }
        ]
      },
      {
        "caption": "V0 detail: agent output exists, but the memory is only transcript",
        "detail": "This is the failure baseline. Ada and Ben can speak, but there is no durable count state, no typed interrupt, and no worker ledger.",
        "hold": 104,
        "burst": true,
        "layout": "focus",
        "focusPane": 0,
        "panes": [
          {
            "imgs": [
              "wt-roomos/RoomOSV0123/v0_02_00.png",
              "wt-roomos/RoomOSV0123/v0_02_01.png",
              "wt-roomos/RoomOSV0123/v0_02_02.png",
              "wt-roomos/RoomOSV0123/v0_02_03.png",
              "wt-roomos/RoomOSV0123/v0_02_04.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 640,
              "y": 520,
              "scale": 1.38
            },
            "prevCursor": {
              "x": 308,
              "y": 679
            },
            "prevZoom": {
              "x": 620,
              "y": 218,
              "scale": 1.18
            },
            "active": false
          },
          {
            "imgs": [
              "wt-roomos/RoomOSV0123/v1_02_00.png",
              "wt-roomos/RoomOSV0123/v1_02_01.png",
              "wt-roomos/RoomOSV0123/v1_02_02.png",
              "wt-roomos/RoomOSV0123/v1_02_03.png",
              "wt-roomos/RoomOSV0123/v1_02_04.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 640,
              "y": 520,
              "scale": 1.38
            },
            "prevCursor": {
              "x": 308,
              "y": 679
            },
            "prevZoom": {
              "x": 620,
              "y": 218,
              "scale": 1.18
            },
            "active": false
          },
          {
            "imgs": [
              "wt-roomos/RoomOSV0123/v2_02_00.png",
              "wt-roomos/RoomOSV0123/v2_02_01.png",
              "wt-roomos/RoomOSV0123/v2_02_02.png",
              "wt-roomos/RoomOSV0123/v2_02_03.png",
              "wt-roomos/RoomOSV0123/v2_02_04.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 640,
              "y": 520,
              "scale": 1.38
            },
            "prevCursor": {
              "x": 308,
              "y": 679
            },
            "prevZoom": {
              "x": 620,
              "y": 218,
              "scale": 1.18
            },
            "active": false
          },
          {
            "imgs": [
              "wt-roomos/RoomOSV0123/v3_02_00.png",
              "wt-roomos/RoomOSV0123/v3_02_01.png",
              "wt-roomos/RoomOSV0123/v3_02_02.png",
              "wt-roomos/RoomOSV0123/v3_02_03.png",
              "wt-roomos/RoomOSV0123/v3_02_04.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 640,
              "y": 520,
              "scale": 1.38
            },
            "prevCursor": {
              "x": 308,
              "y": 679
            },
            "prevZoom": {
              "x": 620,
              "y": 218,
              "scale": 1.18
            },
            "active": false
          }
        ]
      },
      {
        "caption": "Human input: interrupt all rooms and retarget to counting",
        "detail": "The same steer is sent to every live room: count from 1 to 6, one agent per turn, no overlap.",
        "hold": 88,
        "burst": false,
        "layout": "grid",
        "panes": [
          {
            "imgs": [],
            "img": "wt-roomos/RoomOSV0123/v0_03.png",
            "cursor": {
              "x": 953,
              "y": 679
            },
            "click": true,
            "zoom": {
              "x": 640,
              "y": 655,
              "scale": 1.28
            },
            "prevCursor": {
              "x": 308,
              "y": 679
            },
            "prevZoom": {
              "x": 640,
              "y": 520,
              "scale": 1.38
            },
            "active": true
          },
          {
            "imgs": [],
            "img": "wt-roomos/RoomOSV0123/v1_03.png",
            "cursor": {
              "x": 953,
              "y": 679
            },
            "click": true,
            "zoom": {
              "x": 640,
              "y": 655,
              "scale": 1.28
            },
            "prevCursor": {
              "x": 308,
              "y": 679
            },
            "prevZoom": {
              "x": 640,
              "y": 520,
              "scale": 1.38
            },
            "active": true
          },
          {
            "imgs": [],
            "img": "wt-roomos/RoomOSV0123/v2_03.png",
            "cursor": {
              "x": 953,
              "y": 679
            },
            "click": true,
            "zoom": {
              "x": 640,
              "y": 655,
              "scale": 1.28
            },
            "prevCursor": {
              "x": 308,
              "y": 679
            },
            "prevZoom": {
              "x": 640,
              "y": 520,
              "scale": 1.38
            },
            "active": true
          },
          {
            "imgs": [],
            "img": "wt-roomos/RoomOSV0123/v3_03.png",
            "cursor": {
              "x": 953,
              "y": 679
            },
            "click": true,
            "zoom": {
              "x": 640,
              "y": 655,
              "scale": 1.28
            },
            "prevCursor": {
              "x": 308,
              "y": 679
            },
            "prevZoom": {
              "x": 640,
              "y": 520,
              "scale": 1.38
            },
            "active": true
          }
        ]
      },
      {
        "caption": "V1 detail: reducer state makes the count legible",
        "detail": "The transcript shows the agent messages; the roomState strip shows floor, turn, next act, and count progress as authoritative state.",
        "hold": 110,
        "burst": true,
        "layout": "focus",
        "focusPane": 1,
        "panes": [
          {
            "imgs": [
              "wt-roomos/RoomOSV0123/v0_04_00.png",
              "wt-roomos/RoomOSV0123/v0_04_01.png",
              "wt-roomos/RoomOSV0123/v0_04_02.png",
              "wt-roomos/RoomOSV0123/v0_04_03.png",
              "wt-roomos/RoomOSV0123/v0_04_04.png",
              "wt-roomos/RoomOSV0123/v0_04_05.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 650,
              "y": 515,
              "scale": 1.36
            },
            "prevCursor": {
              "x": 953,
              "y": 679
            },
            "prevZoom": {
              "x": 640,
              "y": 655,
              "scale": 1.28
            },
            "active": false
          },
          {
            "imgs": [
              "wt-roomos/RoomOSV0123/v1_04_00.png",
              "wt-roomos/RoomOSV0123/v1_04_01.png",
              "wt-roomos/RoomOSV0123/v1_04_02.png",
              "wt-roomos/RoomOSV0123/v1_04_03.png",
              "wt-roomos/RoomOSV0123/v1_04_04.png",
              "wt-roomos/RoomOSV0123/v1_04_05.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 650,
              "y": 515,
              "scale": 1.36
            },
            "prevCursor": {
              "x": 953,
              "y": 679
            },
            "prevZoom": {
              "x": 640,
              "y": 655,
              "scale": 1.28
            },
            "active": false
          },
          {
            "imgs": [
              "wt-roomos/RoomOSV0123/v2_04_00.png",
              "wt-roomos/RoomOSV0123/v2_04_01.png",
              "wt-roomos/RoomOSV0123/v2_04_02.png",
              "wt-roomos/RoomOSV0123/v2_04_03.png",
              "wt-roomos/RoomOSV0123/v2_04_04.png",
              "wt-roomos/RoomOSV0123/v2_04_05.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 650,
              "y": 515,
              "scale": 1.36
            },
            "prevCursor": {
              "x": 953,
              "y": 679
            },
            "prevZoom": {
              "x": 640,
              "y": 655,
              "scale": 1.28
            },
            "active": false
          },
          {
            "imgs": [
              "wt-roomos/RoomOSV0123/v3_04_00.png",
              "wt-roomos/RoomOSV0123/v3_04_01.png",
              "wt-roomos/RoomOSV0123/v3_04_02.png",
              "wt-roomos/RoomOSV0123/v3_04_03.png",
              "wt-roomos/RoomOSV0123/v3_04_04.png",
              "wt-roomos/RoomOSV0123/v3_04_05.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 650,
              "y": 515,
              "scale": 1.36
            },
            "prevCursor": {
              "x": 953,
              "y": 679
            },
            "prevZoom": {
              "x": 640,
              "y": 655,
              "scale": 1.28
            },
            "active": false
          }
        ]
      },
      {
        "caption": "V2 detail: the interrupt is interpreted as work-room intent",
        "detail": "V2 keeps the human steer visible while using typed intent to retarget the active work instead of treating it as loose chat.",
        "hold": 108,
        "burst": true,
        "layout": "focus",
        "focusPane": 2,
        "panes": [
          {
            "imgs": [
              "wt-roomos/RoomOSV0123/v0_05_00.png",
              "wt-roomos/RoomOSV0123/v0_05_01.png",
              "wt-roomos/RoomOSV0123/v0_05_02.png",
              "wt-roomos/RoomOSV0123/v0_05_03.png",
              "wt-roomos/RoomOSV0123/v0_05_04.png",
              "wt-roomos/RoomOSV0123/v0_05_05.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 640,
              "y": 530,
              "scale": 1.34
            },
            "prevCursor": {
              "x": 953,
              "y": 679
            },
            "prevZoom": {
              "x": 650,
              "y": 515,
              "scale": 1.36
            },
            "active": false
          },
          {
            "imgs": [
              "wt-roomos/RoomOSV0123/v1_05_00.png",
              "wt-roomos/RoomOSV0123/v1_05_01.png",
              "wt-roomos/RoomOSV0123/v1_05_02.png",
              "wt-roomos/RoomOSV0123/v1_05_03.png",
              "wt-roomos/RoomOSV0123/v1_05_04.png",
              "wt-roomos/RoomOSV0123/v1_05_05.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 640,
              "y": 530,
              "scale": 1.34
            },
            "prevCursor": {
              "x": 953,
              "y": 679
            },
            "prevZoom": {
              "x": 650,
              "y": 515,
              "scale": 1.36
            },
            "active": false
          },
          {
            "imgs": [
              "wt-roomos/RoomOSV0123/v2_05_00.png",
              "wt-roomos/RoomOSV0123/v2_05_01.png",
              "wt-roomos/RoomOSV0123/v2_05_02.png",
              "wt-roomos/RoomOSV0123/v2_05_03.png",
              "wt-roomos/RoomOSV0123/v2_05_04.png",
              "wt-roomos/RoomOSV0123/v2_05_05.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 640,
              "y": 530,
              "scale": 1.34
            },
            "prevCursor": {
              "x": 953,
              "y": 679
            },
            "prevZoom": {
              "x": 650,
              "y": 515,
              "scale": 1.36
            },
            "active": false
          },
          {
            "imgs": [
              "wt-roomos/RoomOSV0123/v3_05_00.png",
              "wt-roomos/RoomOSV0123/v3_05_01.png",
              "wt-roomos/RoomOSV0123/v3_05_02.png",
              "wt-roomos/RoomOSV0123/v3_05_03.png",
              "wt-roomos/RoomOSV0123/v3_05_04.png",
              "wt-roomos/RoomOSV0123/v3_05_05.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 640,
              "y": 530,
              "scale": 1.34
            },
            "prevCursor": {
              "x": 953,
              "y": 679
            },
            "prevZoom": {
              "x": 650,
              "y": 515,
              "scale": 1.36
            },
            "active": false
          }
        ]
      },
      {
        "caption": "V3 detail: state, workers, cost, and latency are first-class",
        "detail": "The V3 panel exposes policy, worker budget, expected model cost, expected latency, observed runtime, goals, workers, and artifacts.",
        "hold": 118,
        "burst": true,
        "layout": "focus",
        "focusPane": 3,
        "panes": [
          {
            "imgs": [
              "wt-roomos/RoomOSV0123/v0_06_00.png",
              "wt-roomos/RoomOSV0123/v0_06_01.png",
              "wt-roomos/RoomOSV0123/v0_06_02.png",
              "wt-roomos/RoomOSV0123/v0_06_03.png",
              "wt-roomos/RoomOSV0123/v0_06_04.png",
              "wt-roomos/RoomOSV0123/v0_06_05.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 640,
              "y": 390,
              "scale": 1.26
            },
            "prevCursor": {
              "x": 953,
              "y": 679
            },
            "prevZoom": {
              "x": 640,
              "y": 530,
              "scale": 1.34
            },
            "active": false
          },
          {
            "imgs": [
              "wt-roomos/RoomOSV0123/v1_06_00.png",
              "wt-roomos/RoomOSV0123/v1_06_01.png",
              "wt-roomos/RoomOSV0123/v1_06_02.png",
              "wt-roomos/RoomOSV0123/v1_06_03.png",
              "wt-roomos/RoomOSV0123/v1_06_04.png",
              "wt-roomos/RoomOSV0123/v1_06_05.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 640,
              "y": 390,
              "scale": 1.26
            },
            "prevCursor": {
              "x": 953,
              "y": 679
            },
            "prevZoom": {
              "x": 640,
              "y": 530,
              "scale": 1.34
            },
            "active": false
          },
          {
            "imgs": [
              "wt-roomos/RoomOSV0123/v2_06_00.png",
              "wt-roomos/RoomOSV0123/v2_06_01.png",
              "wt-roomos/RoomOSV0123/v2_06_02.png",
              "wt-roomos/RoomOSV0123/v2_06_03.png",
              "wt-roomos/RoomOSV0123/v2_06_04.png",
              "wt-roomos/RoomOSV0123/v2_06_05.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 640,
              "y": 390,
              "scale": 1.26
            },
            "prevCursor": {
              "x": 953,
              "y": 679
            },
            "prevZoom": {
              "x": 640,
              "y": 530,
              "scale": 1.34
            },
            "active": false
          },
          {
            "imgs": [
              "wt-roomos/RoomOSV0123/v3_06_00.png",
              "wt-roomos/RoomOSV0123/v3_06_01.png",
              "wt-roomos/RoomOSV0123/v3_06_02.png",
              "wt-roomos/RoomOSV0123/v3_06_03.png",
              "wt-roomos/RoomOSV0123/v3_06_04.png",
              "wt-roomos/RoomOSV0123/v3_06_05.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 640,
              "y": 390,
              "scale": 1.26
            },
            "prevCursor": {
              "x": 953,
              "y": 679
            },
            "prevZoom": {
              "x": 640,
              "y": 530,
              "scale": 1.34
            },
            "active": false
          }
        ]
      },
      {
        "caption": "Internal state drawer: the receipts behind the conversation",
        "detail": "The state drawer exposes the reducer snapshot and trace payloads: participants, utterance limits, V3 goals, tasks, workers, artifacts, and world beliefs.",
        "hold": 126,
        "burst": false,
        "layout": "focus",
        "focusPane": 3,
        "panes": [
          {
            "imgs": [],
            "img": "wt-roomos/RoomOSV0123/v0_07.png",
            "cursor": {
              "x": 1147,
              "y": 26
            },
            "click": true,
            "zoom": {
              "x": 133,
              "y": 346,
              "scale": 1.34
            },
            "prevCursor": {
              "x": 953,
              "y": 679
            },
            "prevZoom": {
              "x": 640,
              "y": 390,
              "scale": 1.26
            },
            "active": true
          },
          {
            "imgs": [],
            "img": "wt-roomos/RoomOSV0123/v1_07.png",
            "cursor": {
              "x": 1147,
              "y": 26
            },
            "click": true,
            "zoom": {
              "x": 133,
              "y": 346,
              "scale": 1.34
            },
            "prevCursor": {
              "x": 953,
              "y": 679
            },
            "prevZoom": {
              "x": 640,
              "y": 390,
              "scale": 1.26
            },
            "active": true
          },
          {
            "imgs": [],
            "img": "wt-roomos/RoomOSV0123/v2_07.png",
            "cursor": {
              "x": 1147,
              "y": 26
            },
            "click": true,
            "zoom": {
              "x": 133,
              "y": 346,
              "scale": 1.34
            },
            "prevCursor": {
              "x": 953,
              "y": 679
            },
            "prevZoom": {
              "x": 640,
              "y": 390,
              "scale": 1.26
            },
            "active": true
          },
          {
            "imgs": [],
            "img": "wt-roomos/RoomOSV0123/v3_07.png",
            "cursor": {
              "x": 1147,
              "y": 26
            },
            "click": true,
            "zoom": {
              "x": 335,
              "y": 720,
              "scale": 1.34
            },
            "prevCursor": {
              "x": 953,
              "y": 679
            },
            "prevZoom": {
              "x": 640,
              "y": 390,
              "scale": 1.26
            },
            "active": true
          }
        ]
      },
      {
        "caption": "Final comparison: overview plus readable receipts",
        "detail": "The GIF alternates between all-version context and focused detail so the agent inputs, outputs, roomState, and V3 control plane are readable.",
        "hold": 96,
        "burst": true,
        "layout": "grid",
        "panes": [
          {
            "imgs": [
              "wt-roomos/RoomOSV0123/v0_08_00.png",
              "wt-roomos/RoomOSV0123/v0_08_01.png",
              "wt-roomos/RoomOSV0123/v0_08_02.png",
              "wt-roomos/RoomOSV0123/v0_08_03.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 640,
              "y": 360,
              "scale": 1.14
            },
            "prevCursor": {
              "x": 1147,
              "y": 26
            },
            "prevZoom": {
              "x": 133,
              "y": 346,
              "scale": 1.34
            },
            "active": false
          },
          {
            "imgs": [
              "wt-roomos/RoomOSV0123/v1_08_00.png",
              "wt-roomos/RoomOSV0123/v1_08_01.png",
              "wt-roomos/RoomOSV0123/v1_08_02.png",
              "wt-roomos/RoomOSV0123/v1_08_03.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 640,
              "y": 360,
              "scale": 1.14
            },
            "prevCursor": {
              "x": 1147,
              "y": 26
            },
            "prevZoom": {
              "x": 133,
              "y": 346,
              "scale": 1.34
            },
            "active": false
          },
          {
            "imgs": [
              "wt-roomos/RoomOSV0123/v2_08_00.png",
              "wt-roomos/RoomOSV0123/v2_08_01.png",
              "wt-roomos/RoomOSV0123/v2_08_02.png",
              "wt-roomos/RoomOSV0123/v2_08_03.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 640,
              "y": 360,
              "scale": 1.14
            },
            "prevCursor": {
              "x": 1147,
              "y": 26
            },
            "prevZoom": {
              "x": 133,
              "y": 346,
              "scale": 1.34
            },
            "active": false
          },
          {
            "imgs": [
              "wt-roomos/RoomOSV0123/v3_08_00.png",
              "wt-roomos/RoomOSV0123/v3_08_01.png",
              "wt-roomos/RoomOSV0123/v3_08_02.png",
              "wt-roomos/RoomOSV0123/v3_08_03.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 640,
              "y": 360,
              "scale": 1.14
            },
            "prevCursor": {
              "x": 1147,
              "y": 26
            },
            "prevZoom": {
              "x": 335,
              "y": 720,
              "scale": 1.34
            },
            "active": false
          }
        ]
      }
    ]
  }
];
